FROM python:3.7-slim

# パッケージの追加とタイムゾーンの設定
# 必要に応じてインストールするパッケージを追加してください
RUN apt-get update && apt-get install -y \
    tzdata \
&&  ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
&&  apt-get clean \
&&  rm -rf /var/lib/apt/lists/*

ENV TZ=Asia/Tokyo

# pycaret関係のインストール
RUN apt-get update && apt-get install -y libgomp1
RUN pip install --upgrade pip
RUN pip install --no-cache-dir pycaret==2.3.5


# JupyterLab関連のパッケージ（いくつかの拡張機能を含む）
# 必要に応じて、JupyterLabの拡張機能などを追加してください
RUN python3 -m pip install --upgrade pip \
&&  pip install --no-cache-dir \
    jupyterlab 

RUN mkdir /opt/notebooks

CMD ["jupyter", "lab", "--notebook-dir=/opt", "--ip='*'", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
